### ISSUE TITLE
GAMBIT Unable to synchronously open file (file signature not found)

### ISSUE THREAD

**Issue by alex-trist** [hesslab-gambit/gambit#1]
Dear @jlumpe 

First, thanks for sharing this incredible software.

I want to outline the following issue running GAMBIT.

command: gambit --db "path_to_db" query -s "path_to_single_fasta".fasta

Out: 
Traceback (most recent call last):
  File "/home/microseq/anaconda3/envs/gambit/bin/gambit", line 10, in <module>
    sys.exit(cli())
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/gambit/cli/query.py", line 83, in query_cmd
    sigs = load_signatures(sigfile)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/gambit/sigs/base.py", line 414, in load_signatures
    return load_signatures_hdf5(path, **kw)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/gambit/sigs/hdf5.py", line 229, in load_signatures_hdf5
    return HDF5Signatures(h5.File(path, **kw))
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/microseq/anaconda3/envs/gambit/lib/python3.9/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

I installed GAMBIT using conda and downloaded database as detailed in https://gambit-genomics.readthedocs.io/en/latest/install.html. I've used GAMBIT succesfully in the past, so I tried a fresh installation in a new environment containing only GAMBIT (with python 3.9 and another one with python 3.10), obtainning the same error.

Any ideas of what could it be and how to fix it.

Thanks in advance.

**Comment by jlumpe** [comment]
Thank you for filing this issue. I am closing it as it seems like you got everything working after a reinstall as per your email last week. The problem looks like it might just have been a corrupted database download, but if it happens again let me know.

**Comment by jlumpe** [comment]
Copying the email I just sent you just in case anyone else runs across the same issue:

Upon looking at this more closely, I noticed you were using the wrong command line option. "-s" indicates you are using a pre-computed signatures file for the query. Just omit it and things should work fine.
